#!C:\Users\rugwe\OneDrive\Desktop\pixeltests-wotnot-112fdf1c26cf\backend\venv\Scripts\python.exe
try:
    from gevent import monkey; monkey.patch_all()  # noqa
except ImportError:
    import sys
    sys.stderr.write("error: gevent is missing. Run `pip install gevent`.")
    sys.exit(1)

import sys

from dramatiq.cli import main

if __name__ == "__main__":
    sys.exit(main())
